common:
  # Cache dir for storing data
  cache_dir: "<existing writable folder for caching data>"
dns_providers:
  # List of DNS providers, each having a unique name used below under "domains"
  # A unique name for this DNS provider entry
  - name: "Netcup"
    # Type of DNS provider. Currently, only "Netcup" is supported
    type: "Netcup"
    # The Netcup User ID
    userid: "<netcup-userid>"
    # The Netcup API key
    apikey: "<netcup-apikey>"
    # The Netcup API password
    apipass: "<netcup-apipass>"
router:
  ipv4:
    enabled: true
    # method to resolve public IPv4: "web", "wan" or "fritzbox"
    #method: "web"
    # If method is "web": address of server to query IPv4 from
    #web_url: "http://myexternalip.com/raw"
    # If method is "web": an optional timeout
    #web_timeout: 60
    method: "wan"
    # If method is "wan": Name of the local WAN network interface
    wan_interface: "<put-wan-iface-here>"
    #method: "fritzbox"
    # If method is "fritzbox": IP of Fritz!Box
    #fritzbox_address: "<fritz-box-ip-address>"
    # If method is "fritzbox": Wether or not to use TLS
    #fritzbox_tls: false
  ipv6:
    enabled: true
    # method to resolve public IPv6: "web", "wan" or "fritzbox"
    #method: "web"
    # If method is "web": address of server to query IPv6 from
    #web_url: "http://myexternalip.com/raw"
    # If method is "web": an optional timeout
    #web_timeout: 60
    method: "wan"
    # If method is "wan": Name of the local WAN network interface
    wan_interface: "<put-wan-iface-here>"
    #method: "fritzbox"
    # If method is "fritzbox": IP of Fritz!Box
    #fritzbox_address: "<fritz-box-ip-address>"
    # If method is "fritzbox": Wether or not to use TLS
    #fritzbox_tls: false
domains:
  - name: "test.invalid"
    # Name of the dns provider to be used as onfigured above
    dns_provider: "Netcup"
    # The minimal delay in seconds to wait until next updated. Increase if using dnssec (as resigning the updated records takes quite a lot time)
    delay: 300
    # List of hosts
    hosts:
      # the internal fully qualified domain name
      - name: "openwrt.lan"
        # The public fully qualified domain name
        fqdn: "openwrt.home.test.invalid"
        # method for resolving the desired IP address
        public_ip_methods:
          # the method for IPv4: "router" or "local_dns"
          ipv4: "router"
          # the method for IPv6: "router" or "local_dns"
          ipv6: "router"
        # the internal fully qualified domain name
      - name: "server.lan"
        # The public fully qualified domain name
        fqdn: "server.home.test.invalid"
        # method for resolving the desired IP address
        public_ip_methods:
          # the method for IPv4: "router" or "local_dns"
          ipv4: "router"
          # the method for IPv6: "router" or "local_dns"
          ipv6: "local_dns"
