name: Build docs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install poetry
      run: pip3 install poetry
    - name: Install packages
      run: poetry install
    - name: Build documentation
      run: |
        mkdir gh-pages
        touch gh-pages/.nojekyll
        poetry run sphinx-build -b html docs/source/  gh-pages
    - name: Deploy documentation
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: gh-pages
