name: Release
on:
  release:
    types:
      - created

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: pip3 install poetry && poetry install --with=dev
      - name: Build
        run: poetry build
      - name: Publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          #poetry config repositories.testpypi https://test.pypi.org/legacy/
          #poetry config pypi-token.testpypi $PYPI_TOKEN
          #poetry publish -r testpypi
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish
